services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    command: npm run dev

  worker:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    command: npm run worker

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]