name: Deploy to VPS

on:
  push:
    branches:
      - main # Or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to the app directory
            cd /home/alaqsaka/Screener-Core-TS
            
            # Pull the latest changes from the main branch
            git pull origin main
            
            # Rebuild and restart the services with Docker Compose
            docker compose up -d --build
            
            # Clean up old, unused Docker images to save space
            docker image prune -f
